### ISSUE TITLE
How did you get tmux lazygit and lazydocker in new window to work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [joshmedeski/dotfiles#1]
Hi Josh,
```
bind g new-window -c "#{pane_current_path}" -n "lazygit" lazygit
bind K new-window -c "#{pane_current_path}" -n "lazydocker" lazydocker
```

I've tried calling to edit this file and get it to work, without avail.
which version of tmux are you running?

**Comment by joshmedeski** [comment]
I'm on `v3.3` and it's working okay for me. I suggest killing the tmux server (`tmux kill-server`) and trying again.

My other thought is something is wrong with the config file, feel free to share it and maybe I can spot a bug.
