### ISSUE TITLE
How to install your complete dev environment

### ISSUE THREAD

**Issue by fernandoaleman** [joshmedeski/dotfiles#12]
Hi Josh. I just recently started following your website and YouTube channel and you have some terrific and informative videos. I've watched most of them by now and each has great information, but some use zsh, some use fish and you touch on neovim, lazygit, etc. I've also found your dotfiles repo which also has lots of great config settings, however, not sure which install file is the best one to use to get your current setup. Do you happen to have a video or instructions on how exactly to setup your dev environment step by step? I would love to have my dev environment setup just like yours with alacritty, neovim, tmux, lazygit, lazydocker and minimal macOS window management.

Thanks for all the work you put into your tutorials. I look forward to learning more. 👍

**Comment by joshmedeski** [comment]
Hi @fernandoaleman, thanks for the kind words!

Check out my [dev workflow intro course](https://www.joshmedeski.com/guides/dev-workflow-intro) for free on my website. It will help you get a great starting point.

**Comment by fernandoaleman** [comment]
Thanks @joshmedeski I will follow along and let you know if I have any questions. Have a great day! 👍
