### ISSUE TITLE
shell script

### ISSUE THREAD

**Issue by Alan-MQ** [joshmedeski/dotfiles#13]
Hi there,  I think your work flow is incredible, and the way you combine zoxide and tmux and fzf is just !!!!! blow up my mind,   and I'm very intrested in your t  and tt shell script . But why these two is not in your .config repo ?

**Comment by joshmedeski** [comment]
Thanks @Alan-MQ, it's a tmux plugin now which includes lots of great features since my YouTube video:
https://github.com/joshmedeski/t-smart-tmux-session-manager

**Comment by Alan-MQ** [comment]
> Thanks @Alan-MQ, it's a tmux plugin now which includes lots of great features since my YouTube video: https://github.com/joshmedeski/t-smart-tmux-session-manager

thanks bro, great videos by the way.
