### ISSUE TITLE
Switching Wezterm background keybind

### ISSUE THREAD

**Issue by winter-again** [joshmedeski/dotfiles#14]
Hi Josh. Saw your recent video on Wezterm (glad to see someone talking about Wezterm and how good it is) and how you swap backgrounds on the fly, which is something I aimed to do in a Neovim plugin I built a few months ago. I'm curious about what function/logic you're using to update the background since the keybinding for cmd+R [here](https://github.com/joshmedeski/dotfiles/blob/fdd2012debd8140b113ea994ed25a485064482ad/.config/wezterm/wezterm.lua#L96) seems to be for a source command within Vim. I'm wondering now if I actually overlooked something really simple for swapping backgrounds or other config options.

**Comment by joshmedeski** [comment]
It's not very clear in my dotfiles. The key mapping you linked to is capital "R" (cmd+shift+R) which is a different command.

"Reload Configuration" is a built-in command mapped to `cmd+r` so that's how the feature works, hope that helps.
