### ISSUE TITLE
COMMAND|SHIFT bracket not working with tmux

### ISSUE THREAD

**Issue by brymon68** [joshmedeski/dotfiles#15]
Hey Josh, 

Hope you are well. Ive been playing around with your config for wezterm and am noticing that I cant switch tabs with cmd+shift+[ or cmd+shift+]. Is this expected? I noticed you duplicated the bindings for CTRL+TAB and was wondering if perhaps that was the alternative you switched to / settled for. 

Reference:

https://github.com/joshmedeski/dotfiles/blob/95aeeb0c238d6a4a4cf2f720ddea8a0fbf69fe03/.config/wezterm/wezterm.lua#L115-L130

Appreciate any insight and thanks for all the awesome videos, information and configs you share.

**Comment by joshmedeski** [comment]
Hey, I had the same problem when setting up Wezterm.

You have to go into your keyboard settings and overwrite the default bindings Wezterm set

See https://github.com/wez/wezterm/issues/4251#issuecomment-1718239499

**Comment by brymon68** [comment]
You are an absolute legend. Thank you so much @joshmedeski
