### ISSUE TITLE
No more yabai?

### ISSUE THREAD

**Issue by brymon68** [joshmedeski/dotfiles#16]
Yo josh - just noticed you no longer have yabai / skhd in your dot files. Did you migrate to something else for wm? Sorry for opening issue to ask stupid question!

**Comment by joshmedeski** [comment]
I have simplify my window management solution. I've been getting this question a lot actually, so it may be time to make a new video!

Here's what I'm doing right now as a quick reference.

1. All of my windows are now on one virtual desktop
2. I typically have macOS Stage Manager on. It prevents issues with stacked windows. I can group a couple at a time if needed, but that rarely happens
3. I use [Raycast](https://raycast.com/) to reposition windows if needed, but the majority of the time all my windows fill up all of the monitor.

Hope that helps!
