### ISSUE TITLE
Wezterm config not working on MacOS

### ISSUE THREAD

**Issue by dablurr** [joshmedeski/dotfiles#18]
Hey Josh, 

Stumbled upon your video and wanted to give it a try moving on from Alacritty to Wezterm.

Went ahead and duplicated your config for wez. Therefore, I am having the following issue : 

```
runtime error: /.config/wezterm/utils/helpers.lua:9: bad argument
#1 to 'random' (interval is empty)
stack traceback:
        [C]: in function 'math.random'
        /.config/wezterm/utils/helpers.lua:9: in function 'utils/
helpers.get_random_entry'
        /.config/wezterm/utils/wallpaper.lua:12: in function 'utils/
wallpaper.get_wallpaper'
        [string "/.config/wezterm/wezterm.lua"]:38: in main chunk
```

Does it rings a bell to you ? 

Config is identical to the one from this repo. 

Cheers Josh

**Comment by joshmedeski** [comment]
You'll want to make sure the wallpaper logic is pointing to a valid path on your machine with image files inside.

https://github.com/joshmedeski/dotfiles/blob/90bb7e4393fa797e374d970c18705660a16ff593/.config/wezterm/wezterm.lua?plain=1#L23

**Comment by dablurr** [comment]
You were right indeed. Working now. Thanks Josh 👏

**Comment by joshmedeski** [comment]
You're welcome, hope you enjoy Wezterm!
