### ISSUE TITLE
`nvim` slow to start, for git commit

### ISSUE THREAD

**Issue by jdhoffa** [joshmedeski/dotfiles#6]
With `nvim` set as the default git editor, when running `git commit`, I notice nvim is rather slow to start. 
This is of course avoided entirely if using `lazygit`, or if specifying the commit message directly in the command-line. 

I'm mainly opening this issue as a discussion. I'm curious if you also notice the same thing on your machine, or if it's something in my personal config that slows it down?

**Comment by joshmedeski** [comment]
I've noticed it too. I looked into it tonight and couldn't find the source.

For now, you can switch the git editor to vi (which is really fast).

p.s. I'm making the switch to [LazyVim](https://github.com/LazyVim/LazyVim) right now so my whole config will have big breaking changes soon (which will fix this issue).
