### ISSUE TITLE
Gitmux

### ISSUE THREAD

**Issue by hqkhan** [joshmedeski/dotfiles#8]
Hi @joshmedeski. I was in the process of taking some pieces from your config as I really like it. Specifically, I wanted to have your `gitmux` config and change some of the colors later on. But whenever I try your config, gitmux just doesn't output anything in tmux. 

Here's what it looks like. I'm not sure why the spacing for tmux-window-names is off but I'll deal with that later.

<img width="179" alt="image" src="https://user-images.githubusercontent.com/22674069/224881943-e7016b72-5cfe-4f5a-8602-f74272724e43.png">

Relevant tmux config:

```
set -g status-left  '#[fg=blue,bold]#S #[fg=white,nobold]'
set -ga status-left '#(gitmux -cfg $HOME/.config/tmux/gitmux.conf)'
# set -ga status-left                 '#[fg=white,nobold]#(gitmux -timeout 200ms -cfg $HOME/.config/tmux/gitmux.conf "#{pane_current_path}") '
# set -g status-right '#(gitmux -cfg $HOME/.config/tmux/gitmux.conf "#{pane_current_path}")'
```

I tried a couple other lines as shown in comments but none have worked. I tried opening an [issue](https://github.com/arl/gitmux/issues/89) on `gitmux` github but the author wasn't able to answer. Thought I'd check in as it can't hurt. Do you know what could be wrong?

**Comment by joshmedeski** [comment]
Is `config` a git repository? The base directory you open the tmux session on has to be a git repository.

**Comment by hqkhan** [comment]
I forgot to include it in the original post. `config` is not a git repository. I've tried what you mentioned before which still doesn't make it show up. Below is a picture of my yadm repo. I've tried it with a non-bare repo which still doesn't work. The below image is me in my bare yadm repo where I can issue git commands. I can confirm that gitmux is able to pick up changes, etc but it does not show up on my bar as you can see on the top left. 

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/22674069/225052656-2b9c6d6d-ced6-4d55-886d-56d6b37be753.png">

**Comment by joshmedeski** [comment]
My only thought is the tmux environment can't detect the path to gitmux. Can you run `which gitmux` and let me know the output? Perhaps the `PATH` is setup incorrectly and tmux can't detect the gitmux binary.

**Comment by hqkhan** [comment]
I think you are right on the money actually. `which gitmux` will work fine because I'm calling the binary in the image. One "wonky" thing that exists in my setup is that by default, my system is set to be using `zsh`. In tmux, I tell it to use `/bin/bash` like so:

```
set-option -g default-shell "/bin/bash"
set -g default-command "/bin/bash"
```

However, when I did this:

```
bind-key g new-window -n '' send-keys "lazygit" Enter
```

It didn't work as the window tmux spawned is trying to call `lazygit` binary which isn't on the `PATH` for `zsh` (I don't really have zsh configured; been meaning to switch to it from bash). 

I *think* the problem will be fixed if I add linuxbrew path to `PATH`. I'm on a host my work provides and the setup is a bit tricky. I can't change default shells via `chsh` as it doesn't exist for me.

**Comment by joshmedeski** [comment]
You'll have to add the path you installed gitmux and lazygit to your zsh $PATH then. Please let me know if you get it working :)

**Comment by hqkhan** [comment]
So, I think it does work when I don't use my config. I copied your config verbatim but it hates this line:

```
set -g status-right  '#[fg=blue,bold]#S #[fg=white,nobold]'
set -g status-right '#(gitmux -cfg $HOME/.config/tmux/gitmux.conf)'
```

If I do:

```
set -g status-right '#(gitmux "#{pane_current_path}")'
```

It will work as in the status bar is fine with the defaults. I'm curious as to how yours works without `#{pane_current_path}"`. The docs for `gitmux` mention:

```
set -g status-right '#(gitmux -cfg $HOME/.gitmux.conf "#{pane_current_path}")'
```

**Comment by joshmedeski** [comment]
So to my knowledge, it looks at the root directory of the tmux session, which is what I want since my tmux sessions are usually tied to a git repository. I don't want it changing if I cd into a different place in a tmux pane.

Hope that makes sense and glad we figured out your issue.

**Comment by hqkhan** [comment]
Ty for your help!
